#################################
## Astronomer Prisma ConfigMap ##
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prisma-config
  labels:
    component: prisma
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  config.yml: |
    port: {{ .Values.ports.prismaHTTP }}
    managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
    databases:
      default:
        connector: postgres
        {{- if not .Values.pgbouncer.enabled }}
        uri: $PRISMA_DB_URI
        {{ else }}
        # we need this format to support users like: astro@astro-azure
        host: {{ template "pgbouncer_host" . }}
        port: {{ .Values.ports.pgbouncer }}
        user: postgres
        password: postgres
        database: postgres
        {{- end }}
        migrations: true
        # 2 is the minimum allowed value
        # There is one connection reserved
        # for management operations, so the queries
        # can make use of one less than the configured
        # number here.
        connectionLimit: 5
